# Generated by Django 3.2.8 on 2023-07-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReIssuePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fare_difference', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gozayaan_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airline_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.airlinefee')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gozayaan_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airline_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.airlinefee')),
            ],
        ),
    ]
