# Generated by Django 3.2.8 on 2023-07-24 05:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlinePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100, unique=True)),
                ('content', ckeditor.fields.RichTextField(default="Cancellation\nCancellation Fee = Airline's Fee + Ural Tours Fee\nRefund Amount = Paid Amount - Cancellation Fee\nRe-issue\nRe-issue Fee = Airline's Fee + Fare Difference + Ural Tours Fee\n*The airline's fee is indicative and per person. Convenience fee is non-refundable.")),
            ],
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='airline_fee',
        ),
        migrations.RemoveField(
            model_name='reissuepolicy',
            name='airline_fee',
        ),
        migrations.DeleteModel(
            name='AirlineFee',
        ),
        migrations.DeleteModel(
            name='CancellationPolicy',
        ),
        migrations.DeleteModel(
            name='ReIssuePolicy',
        ),
    ]
