# Generated by Django 3.2.8 on 2023-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20230724_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinepolicy',
            name='airline_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
